// ================================================================
// La Paz — Edge Function: simulate-match
// Match Prediction (API_CONTRACT.md §5, AI_PROMPTS.md §3)
// ================================================================

import { serve } from "https://deno.land/std@0.208.0/http/server.ts";
import { getSupabaseClient, getUserFromRequest, getClientIp } from "../_shared/supabase.ts";
import { handleCors, corsHeaders } from "../_shared/cors.ts";
import { SimulateMatchRequestSchema, validateRequest } from "../_shared/validate.ts";
import { createSSEStream, type SSEWriter } from "../_shared/sse.ts";
import { callAI, getErrorMessage } from "../_shared/ai-client.ts";
import { checkRateLimit, logFanEvent } from "../_shared/rate-limit.ts";
import type { MatchSimulationResult } from "../_shared/types.ts";

// --- Prompt (AI_PROMPTS.md §3) ---

const MATCH_SYSTEM_PROMPT = `You are a football match analyst AI for La Paz platform.
This analysis is for FAN ENTERTAINMENT purposes only — NOT for gambling.

## STRICT RULES
1. Base predictions ONLY on the provided team statistics, recent form, and head-to-head data.
2. Do NOT invent match results, statistics, or historical records not in the context.
3. If critical data (e.g., head-to-head records) is missing, state so explicitly.
4. Win probabilities must sum to exactly 100.
5. Always include the disclaimer about entertainment purpose.

## ANALYSIS FRAMEWORK
- Recent Form: Last 5 matches performance
- Head-to-Head: Historical matchups between the two teams
- Key Factors: Injuries, home advantage, tactical matchups
- Statistical Comparison: Goals scored/conceded, xG, possession`;

const MATCH_DISCLAIMER_KO =
  "이 예측은 통계 데이터 기반의 팬 엔터테인먼트 콘텐츠입니다. 도박 또는 베팅 목적으로 사용할 수 없으며, 실제 경기 결과와 다를 수 있습니다. AI가 생성한 분석입니다.";

const MATCH_DISCLAIMER_EN =
  "This prediction is fan entertainment content based on statistical data. It cannot be used for gambling or betting purposes and may differ from actual match results. This analysis was generated by AI.";

const MATCH_SCHEMA = {
  type: "object" as const,
  properties: {
    predicted_score: {
      type: "object",
      properties: {
        home: { type: "number" },
        away: { type: "number" },
      },
      required: ["home", "away"],
    },
    win_probability: {
      type: "object",
      properties: {
        home: { type: "number" },
        draw: { type: "number" },
        away: { type: "number" },
      },
      required: ["home", "draw", "away"],
    },
    key_factors: { type: "array", items: { type: "string" } },
    head_to_head_analysis: { type: "string" },
    form_analysis: {
      type: "object",
      properties: {
        home: { type: "string" },
        away: { type: "string" },
      },
      required: ["home", "away"],
    },
    disclaimer: { type: "string" },
  },
  required: [
    "predicted_score",
    "win_probability",
    "key_factors",
    "head_to_head_analysis",
    "form_analysis",
    "disclaimer",
  ],
};

serve(async (req: Request) => {
  const corsResp = handleCors(req);
  if (corsResp) return corsResp;

  if (req.method !== "POST") {
    return new Response(
      JSON.stringify({ error: { code: "INVALID_INPUT", message: "Method not allowed" } }),
      { status: 405, headers: { ...corsHeaders, "Content-Type": "application/json" } },
    );
  }

  let body: unknown;
  try {
    body = await req.json();
  } catch {
    return new Response(
      JSON.stringify({ error: { code: "INVALID_INPUT", message: "Invalid JSON" } }),
      { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } },
    );
  }

  const validation = validateRequest(SimulateMatchRequestSchema, body);
  if (!validation.success) {
    return new Response(
      JSON.stringify({ error: { code: "INVALID_INPUT", message: validation.error } }),
      { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } },
    );
  }

  const { home_team_id, away_team_id } = validation.data;
  const supabase = getSupabaseClient();
  const userId = getUserFromRequest(req);
  const clientIp = getClientIp(req);

  // Rate limit
  const rateLimit = await checkRateLimit(supabase, userId, clientIp);
  if (!rateLimit.allowed) {
    return new Response(
      JSON.stringify({ error: { code: "RATE_LIMITED", message: getErrorMessage("rate_limit") } }),
      { status: 429, headers: { ...corsHeaders, "Content-Type": "application/json" } },
    );
  }

  // Validate teams
  const [homeRes, awayRes] = await Promise.all([
    supabase.from("teams").select("id, name").eq("id", home_team_id).maybeSingle(),
    supabase.from("teams").select("id, name").eq("id", away_team_id).maybeSingle(),
  ]);

  if (!homeRes.data || !awayRes.data) {
    return new Response(
      JSON.stringify({
        error: {
          code: "INVALID_INPUT",
          message: !homeRes.data ? "Home team not found" : "Away team not found",
        },
      }),
      { status: 404, headers: { ...corsHeaders, "Content-Type": "application/json" } },
    );
  }

  return createSSEStream(async (writer: SSEWriter) => {
    const startTime = Date.now();

    // 1. Send metadata
    writer.send("metadata", {
      ai_generated: true,
      simulation_type: "match",
    });

    // 2. Gather data
    const [
      homeStatsRes,
      awayStatsRes,
      homeRecentRes,
      awayRecentRes,
      h2hRes,
      homeInjuriesRes,
      awayInjuriesRes,
    ] = await Promise.all([
      // Team season stats
      supabase
        .from("team_season_stats")
        .select("*")
        .eq("team_id", home_team_id)
        .order("created_at", { ascending: false })
        .limit(1)
        .maybeSingle(),
      supabase
        .from("team_season_stats")
        .select("*")
        .eq("team_id", away_team_id)
        .order("created_at", { ascending: false })
        .limit(1)
        .maybeSingle(),
      // Recent 5 matches
      supabase
        .from("matches")
        .select("id, match_date, home_team_id, away_team_id, home_score, away_score")
        .or(`home_team_id.eq.${home_team_id},away_team_id.eq.${home_team_id}`)
        .not("home_score", "is", null)
        .order("match_date", { ascending: false })
        .limit(5),
      supabase
        .from("matches")
        .select("id, match_date, home_team_id, away_team_id, home_score, away_score")
        .or(`home_team_id.eq.${away_team_id},away_team_id.eq.${away_team_id}`)
        .not("home_score", "is", null)
        .order("match_date", { ascending: false })
        .limit(5),
      // Head-to-head
      supabase
        .from("matches")
        .select("id, match_date, home_team_id, away_team_id, home_score, away_score")
        .or(
          `and(home_team_id.eq.${home_team_id},away_team_id.eq.${away_team_id}),and(home_team_id.eq.${away_team_id},away_team_id.eq.${home_team_id})`,
        )
        .not("home_score", "is", null)
        .order("match_date", { ascending: false })
        .limit(10),
      // Injuries (active)
      supabase
        .from("injuries")
        .select("player_id, players(name), injury_type")
        .eq("team_id", home_team_id)
        .is("end_date", null)
        .limit(10),
      supabase
        .from("injuries")
        .select("player_id, players(name), injury_type")
        .eq("team_id", away_team_id)
        .is("end_date", null)
        .limit(10),
    ]);

    // Build context
    const contextParts = [
      `Home Team: ${homeRes.data.name}`,
      `Home Team Season Stats:\n${JSON.stringify(homeStatsRes.data ?? {}, null, 2)}`,
      `Home Team Recent 5 Matches:\n${JSON.stringify(homeRecentRes.data ?? [], null, 2)}`,
      `Home Team Active Injuries:\n${JSON.stringify(homeInjuriesRes.data ?? [], null, 2)}`,
      `\nAway Team: ${awayRes.data.name}`,
      `Away Team Season Stats:\n${JSON.stringify(awayStatsRes.data ?? {}, null, 2)}`,
      `Away Team Recent 5 Matches:\n${JSON.stringify(awayRecentRes.data ?? [], null, 2)}`,
      `Away Team Active Injuries:\n${JSON.stringify(awayInjuriesRes.data ?? [], null, 2)}`,
      `\nHead-to-Head Record:\n${JSON.stringify(h2hRes.data ?? [], null, 2)}`,
    ];

    const contextPrompt = `${MATCH_SYSTEM_PROMPT}

## INPUT CONTEXT
${contextParts.join("\n")}`;

    // 3. Claude AI structured output
    let result: MatchSimulationResult | null = null;
    let modelUsed = "claude-sonnet-4-20250514";

    for await (const event of callAI(
      contextPrompt,
      `Predict the outcome of ${homeRes.data.name} (home) vs ${awayRes.data.name} (away). Include the fixed disclaimer text.`,
      {
        maxTokens: 2048,
        temperature: 0.3,
        timeoutMs: 60_000,
        tools: [{
          name: "predict_match",
          description: "Predict a football match outcome based on statistics",
          input_schema: MATCH_SCHEMA,
        }],
        toolChoice: { type: "tool", name: "predict_match" },
      },
    )) {
      if (event.event === "result") {
        // Ensure disclaimer is the fixed text
        const data = event.data as Record<string, unknown>;
        data.disclaimer = MATCH_DISCLAIMER_KO;
        result = data as unknown as MatchSimulationResult;
        writer.send("result", data);
      } else if (event.event === "error") {
        writer.send("error", event.data);
        if (!(event.data as { fallback: boolean }).fallback) return;
      } else if (event.event === "done") {
        modelUsed = (event.data as { model: string }).model;
      }
    }

    // 4. Save to simulations table
    const { data: sim } = await supabase
      .from("simulations")
      .insert({
        user_id: userId,
        sim_type: "match",
        params: { home_team_id, away_team_id },
        result: result ?? {},
        model_used: modelUsed,
        latency_ms: Date.now() - startTime,
      })
      .select("id")
      .single();

    // 5. Update fan_predictions ai_prediction (if applicable match exists)
    if (result) {
      const { data: matchRow } = await supabase
        .from("matches")
        .select("id")
        .eq("home_team_id", home_team_id)
        .eq("away_team_id", away_team_id)
        .is("home_score", null)
        .order("match_date", { ascending: true })
        .limit(1)
        .maybeSingle();

      if (matchRow) {
        await supabase
          .from("fan_predictions")
          .update({
            ai_prediction: {
              predicted_score: result.predicted_score,
              win_probability: result.win_probability,
              model: modelUsed,
              simulation_id: sim?.id,
            },
          })
          .eq("match_id", matchRow.id);
      }
    }

    // 6. Done event (SSE_FORMAT.md §2.5)
    writer.send("done", {
      simulation_id: sim?.id ?? null,
      model: modelUsed,
      latency_ms: Date.now() - startTime,
      tokens_used: 0,
    });

    // 7. Async: log fan event
    logFanEvent(supabase, {
      userId,
      eventType: "simulation",
      clientIp,
      payload: {
        sim_type: "match",
        home_team_id,
        away_team_id,
        model: modelUsed,
      },
    }).catch(() => {});
  });
});
